
server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mySuperSecureKey_mySuperSecureKey_123456
  access-expiration: 36000000 # MATCHED TO YOUR JAVA VARIABLE

security:
  user:
    name: ""
    password: ""